# Generated by Django 5.2.4 on 2025-07-29 21:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postulante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'PROGRAMADO'), ('EN_PROCESO', 'EN_PROCESO'), ('CERRADO', 'CERRADO')], default='CERRADO', max_length=20)),
                ('resultado_puntaje', models.FloatField()),
                ('resultado_aprobado', models.BooleanField()),
                ('resultado_comentario', models.TextField(blank=True, default='')),
                ('resultado_fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='postulante.postulantemodel')),
            ],
        ),
    ]
