# Generated by Django 5.2.4 on 2025-07-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20)),
                ('monto', models.FloatField()),
                ('servicio', models.CharField(max_length=100)),
                ('estado_transaccion', models.BooleanField()),
            ],
        ),
    ]
