# Generated by Django 5.2.4 on 2025-07-29 01:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postulante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('moneda', models.CharField(max_length=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO')], max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='postulante.postulantemodel')),
            ],
        ),
    ]
