# Generated by Django 5.2.4 on 2025-07-29 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0001_initial'),
        ('postulante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionBancariaModel',
            fields=[
                ('id_transaccion', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('banco', models.CharField(max_length=100)),
                ('monto', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='pagomodel',
            old_name='fecha_pago',
            new_name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='pagomodel',
            name='postulante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulante.postulantemodel'),
        ),
        migrations.AddField(
            model_name='pagomodel',
            name='transaccion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pago.transaccionbancariamodel'),
        ),
    ]
